### ISSUE TITLE
build error: undefined reference

### ISSUE THREAD

**Issue by schmidicom** [JvanKatwijk/sdr-j-dab#2]
When i try to build this Software for my Gentoo Linux stops make with the following Error:
[build-error.txt](https://github.com/JvanKatwijk/sdr-j-dab/files/327861/build-error.txt)

And here my custom unix section of sdr-j-dab-0994.pro:
```
unix {
CONFIG		+= dabstick_osmo
#CONFIG		+= dabstick_new
#CONFIG		+= sdrplay
CONFIG		+= rtl_tcp
#CONFIG		+= airspy
#CONFIG		+= airspy-exp
CONFIG		+= spectrum
DEFINES		+= MOT_BASICS__ 	# use at your own risk
DEFINES		+= MSC_DATA__		# use at your own risk
DESTDIR		= ./linux-bin
INCLUDEPATH	+= /usr/include/qwt6 /usr/local/include
LIBS		+= -lqwt -lfftw3f  -lrtlsdr  -lusb-1.0 -ldl	 # ubuntu
#LIBS		+= -lqwt-qt5 -lfftw3f  -lrtlsdr  -lusb-1.0 -ldl  # fedora
LIBS		+= -lportaudio
LIBS		+= -lsndfile
LIBS		+= -lfaad
}
```
My Software:
- qwt 5.2.3
- qwt 6.1.0
- qt 5.6.1
- libusb 1.0.19
- portaudio 0.19
- fftw 3.3.4
- rtl-sdr 0.5.3
- faad2 2.7
- libsndfile 1.0.26

**Comment by JvanKatwijk** [comment]
Afais the qwt lib is not found
Op 22 jun. 2016 15:06 schreef "Stefan Schmid" <notifications@github.com>:

**Comment by schmidicom** [comment]
But the library is installed:
[installed-qwt6-files.txt](https://github.com/JvanKatwijk/sdr-j-dab/files/328080/installed-qwt6-files.txt)
And now?

**Comment by JvanKatwijk** [comment]
The errors you presented result from the make process not finding the qwt
library, so if you have installed the qwt library you probably have to
adapt the pro file to include the correct lib path
Op 22 jun. 2016 16:24 schreef "Stefan Schmid" <notifications@github.com>:

**Comment by schmidicom** [comment]
I must apologize that qmake file must be well adapted more for gentoo than expected.
```
unix {
#CONFIG		+= dabstick_osmo
#CONFIG		+= dabstick_new
#CONFIG		+= sdrplay
CONFIG		+= rtl_tcp
#CONFIG		+= airspy
#CONFIG		+= airspy-exp
CONFIG		+= spectrum
DEFINES		+= MOT_BASICS__ 	# use at your own risk
DEFINES		+= MSC_DATA__		# use at your own risk
DESTDIR		= ./linux-bin
INCLUDEPATH	+= /usr/include/qwt6 /usr/include
LIBS		+= -L/usr/lib64/ -lqwt6 -lfftw3f  -lrtlsdr  -lusb-1.0 -ldl
LIBS		+= -L/usr/lib64/ -lportaudio
LIBS		+= -L/usr/lib64/ -lsndfile
LIBS		+= -L/usr/lib64/ -lfaad
}
```
So this is not a bug, sorry.
